name: Upload to S3

on:
  push:
    branches:
      - master
    paths:
      - ./site/**
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Copy file to S3
        shell: bash
        env:
          access_key: ${{ secrets.ACCESS_TOKEN }}
          secret_key: ${{ secrets.SECRET_KEY }}
          s3_bucket: ${{ secrets.BUCKET_NAME }}
        run: |
          aws configure set aws_access_key_id $access_key
          aws configure set aws_secret_access_key $secret_key 
          aws configure set default.region us-east-2
          aws s3 sync --delete ./site/ s3://$s3_bucket/
